version: 2

project_name: kubectl-shovel
builds:
- binary: kubectl-shovel
  id: general
  main: ./cli/main.go
  ldflags:
  - -s -w -X 'github.com/dodopizza/kubectl-shovel/internal/globals.Version=v{{ .Version }}'
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64
archives:
- id: default
  name_template: '{{ .ProjectName }}_{{ .os }}_{{ .arch }}{{ if .arm }}v{{ .arm }}{{ end }}'
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE
replacements:
  darwin: Darwin
  linux: Linux
  windows: Windows
  amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
  exclude:
  - 'typo'
  - 'static check'
  - 'lint'
  - 'format'
  - 'tidy'
release:
  name_template: "{{ .ProjectName }}-v{{ .Version }}"
  prerelease: auto