apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: shovel
spec:
  homepage: https://github.com/dodopizza/kubectl-shovel
  shortDescription: Gather diagnostics for .NET Core applications
  version: {{ .TagName }}
  description: |
    Plugin for gathering diagnostics from running in Kubernetes .NET Core
    applications. It runs the job on the specified pod's node with a mount
    to its /tmp folder with application's diagnostic socket and runs specified
    tool against it. Supported tools are: dotnet-gcdump and dotnet-trace
  caveats: |
    It can work with .NET Core 3.0+ applications and Kubernetes clusters with
    docker or containerd runtime. Permissions to get pods and create jobs are
    required. Also it requires allowance to mount /var/lib/docker path for
    docker runtime and /run/containerd for containerd from a host in read-only
    mode
  platforms:
    - {{addURIAndSha "https://github.com/dodopizza/kubectl-shovel/releases/download/{{ .TagName }}/kubectl-shovel_Darwin_x86_64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-shovel
      files:
        - from: kubectl-shovel
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: darwin
          arch: amd64
    - {{addURIAndSha "https://github.com/dodopizza/kubectl-shovel/releases/download/{{ .TagName }}/kubectl-shovel_Darwin_arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-shovel
      files:
        - from: kubectl-shovel
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: darwin
          arch: arm64
    - {{addURIAndSha "https://github.com/dodopizza/kubectl-shovel/releases/download/{{ .TagName }}/kubectl-shovel_Linux_x86_64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-shovel
      files:
        - from: kubectl-shovel
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: linux
          arch: amd64
    - {{addURIAndSha "https://github.com/dodopizza/kubectl-shovel/releases/download/{{ .TagName }}/kubectl-shovel_Linux_arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-shovel
      files:
        - from: kubectl-shovel
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: linux
          arch: arm64
    - {{addURIAndSha "https://github.com/dodopizza/kubectl-shovel/releases/download/{{ .TagName }}/kubectl-shovel_Windows_x86_64.zip" .TagName | indent 6 }}
      bin: kubectl-shovel.exe
      files:
        - from: kubectl-shovel.exe
          to: .
        - from: LICENSE
          to: .
      selector:
        matchLabels:
          os: windows
          arch: amd64
