---
name: Testing and publishing

on:
  pull_request: {}
  push:
    paths-ignore:
    - '*.md'
    - '**/*.md'
    branches:
    - master
    tags:
    - "*"

env:
  GOLANG_VERSION: "^1.24.1"

jobs:
  doc:
    name: Check doc freshness
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOLANG_VERSION }}
    - name: Run doc generation
      run: |
        make doc
    - name: Check if working tree is dirty
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          git diff
          echo 'run `make doc` or `make prepare` and commit changes'
          exit 1
        fi

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.64.6
        github-token: ${{ secrets.GITHUB_TOKEN }}
        args: "--fix=false --timeout=10m"

  tidy:
    name: Mod tidy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOLANG_VERSION }}
    - name: Run tidy
      run: |
        make tidy
    - name: Check if working tree is dirty
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          git diff
          echo 'run `make tidy` or `make prepare` and commit changes'
          exit 1
        fi

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOLANG_VERSION }}
    - name: Run tests
      run: |
        make test-unit

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        framework:
        - netcoreapp3.1
        - net5.0
        - net6.0
        - net7.0
        - net8.0
        - net9.0
    needs:
    - doc
    - lint
    - tidy
    - test
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOLANG_VERSION }}
    - name: Setup Kubernetes
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.11.1
        image: kindest/node:v1.21.1
    - name: Run tests
      run: |
        make test-integration FRAMEWORK=${{ matrix.framework }}

  publish-dumper:
    name: Publishing dumper docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
          go-version: ${{ env.GOLANG_VERSION }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker build and push for multi-arch
      uses: docker/build-push-action@v5
      with:
        context: ./dumper
        file: ./dumper/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          dodopizza/kubectl-shovel-dumper:v0.9.2-dev
          dodopizza/kubectl-shovel-dumper:v0.9.2-test
        cache-from: type=gha
        cache-to: type=gha,mode=max

  publish-cli:
    name: Publishing cli
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    needs:
    - integration-tests
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOLANG_VERSION }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update new version in krew-index
      if: ${{ !contains(github.ref, 'beta') }}
      uses: rajatjindal/krew-release-bot@v0.0.38
